// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlbqiqlonpihrruufyix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsYnFpcWxvbnBpaHJydXVmeWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDkzNDUsImV4cCI6MjA2OTQyNTM0NX0.fuh03Cog6xgw3NKtW9_oY1AeB-Sgfam3zoHQp8CbpHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});